version: "3.7"

networks:
  apinetwork:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-172.30.0.0/24}
          gateway: ${DOCKER_GATEWAY:-172.30.0.1}

services:
  api:
    image: golang:1.23.3-bullseye
    build: .
    volumes:
      - .:/app/go_service
      - go_environment:/go
    working_dir: /app/go_service
    command: bash -c "go mod download && go run main.go -host=${API_HOST:-0.0.0.0} -port=${API_PORT:-8080}"
    ports: 
      - ${API_PORT:-8080}:${API_PORT:-8080} 
    networks:
      apinetwork:
        ipv4_address: ${API_HOST:-172.30.0.2}

volumes:
  go_environment:
